"""Eight regression cases plus four prospective transfer cases; no case retries.

A new bounded explanation contract is recorded before inference. No previous
result is relabeled. All twelve cases must meet the same semantic floor.
"""
import argparse
from pathlib import Path
import simulator as s
import qualify as old

def make_cases():
 cases=old.make_cases()
 for x in cases:x['case']['case_id']='K'+s.sha((x['case']['title']+'qualification-v3-bounded').encode())[:12]
 extra=[
 ('Historical explanation','specification_handoff','artifact_review','Check whether the declared historical-rationale requirement has supporting evidence.',
  'This bounded review requires a contemporaneous record of the original choice and its reason. A new explanation is not evidence of original author intent.',
  'The only explanation was generated by an assistant this morning, after the design was produced. No historical author record or observed contradiction is available.',
  'insufficient_evidence','request_evidence'),
 ('Keyboard design walkthrough','prototype_handoff','artifact_review','Inspect this prototype review only, not the production implementation.',
  'The sole requirement is a documented keyboard focus path and a retained prototype walkthrough. Runtime code tests are outside this declared stage.',
  'The focus path is defined in revision K4 and the retained K4 walkthrough covers it with conformance. Nothing in the declared scope is omitted or observed to fail.',
  'sufficient_for_declared_scope','continue_declared_review'),
 ('Tenant runtime boundary','runtime_release_review','artifact_review','Review the evidence of the current runtime boundary only. Do not authorize release.',
  'Revision T2 requires accounts from different tenants to be unable to see each other records. An executed check on T2 is required.',
  'A retained T2 execution shows an account retrieving another tenant record. The required check was performed and clearly failed.',
  'demonstrated_failure','revise'),
 ('Acknowledgment recovery','implementation_review','artifact_review','Review both declared acknowledgment and retry requirements for implementation handoff.',
  'Both duplicate suppression and reliable acknowledgment need code evidence and executed checks for revision A7.',
  'Code records exist for both. The A7 duplicate test creates two objects for one request and fails. The acknowledgment requirement has no executed check.',
  'mixed_failure_and_missing','revise')]
 for title,stage,route,request,contract,evidence,state,rec in extra:
  case={'schema_version':'1.0','case_id':'K'+s.sha((title+'qualification-v3-bounded').encode())[:12],
   'instructions':'Constructed qualification vignette. Use only the supplied records; absent evidence must not be invented.',
   'title':title,'request':request,'artifact_stage':stage,'records':[
    {'id':'R01','title':'Declared review contract','text':contract},
    {'id':'R02','title':'Available evidence','text':evidence},
    {'id':'R03','title':'Origin and authority','text':'These are authored synthetic records, not a human participant study. No owner or deployment authorization has been granted.'}]}
  cases.append({'case':case,'expected':{'review_route':route,'evidence_state':state,'recommendation':rec}})
 return cases

def main():
 a=argparse.ArgumentParser();a.add_argument('--protocol',required=True);a.add_argument('--out',required=True);a.add_argument('--native');a.add_argument('--shard',type=int,required=True);v=a.parse_args()
 if v.shard not in (1,2,3,4):raise ValueError('UNKNOWN_SHARD')
 out=Path(v.out);out.mkdir(parents=True,exist_ok=False)
 material=Path(v.protocol).read_text()
 if s.sha(material.encode())!=s.PROTOCOL_SHA256:raise ValueError('PROTOCOL_DRIFT')
 cases=make_cases();s.write_json(out/'cases.controller.json',cases)
 plan={'version':'operational-qualification-v3-bounded','model':s.MODEL,'revision':s.REVISION,'weight_sha256':s.WEIGHT_SHA256,
  'runtime':'llama.cpp b11146','protocol_sha256':s.PROTOCOL_SHA256,'cases_sha256':s.sha(s.canonical(cases)),
  'floor':'12/12 predefined categorical, citation, no-fabricated-human and no-authority-overreach checks; necessary not human validation',
  'max_calls':14,'shards':4,'call_timeout_seconds':240,'retries':0,'grammar':'same outcome options; bounded explanation lengths only',
  'instruction_sha256':s.sha(s.INSTRUCTION.encode()),'schema_sha256':s.sha(s.canonical(s.schema())),
  'post_outcome_semantic_threshold_tuning':False,'prior_version_result':'v010:2 of 8 operational cases passed; six length truncations preserved',
  'selection':'all eight regression cases plus four newly authored transfer cases before v011 inference'}
 s.write_json(out/'pre-inference-plan.json',plan)
 client=s.ModelClient();rows=[]
 if v.shard==1:
  old.personas(v.native,out)
  for i,text in enumerate(['A green square is beside a red circle. Restate one shape.','A room opens at 08:00 and closes at 16:00. Restate one time.']):
   case={'schema_version':'1.0','case_id':'K'+str(i+1)*12,'instructions':'Neutral connectivity only. A review judgment is not requested.','title':'Neutral note','request':text,'artifact_stage':'not_applicable','records':[{'id':'R01','title':'Note','text':text}]}
   result=client.call(s.request_for(case,'',seed=20260928+i),out/f'smoke-{i+1}')
   print('SIM_NEUTRAL '+s.canonical({'id':i+1,'status':result['status']}).decode(),flush=True)
   if result['status']=='transport_error':raise RuntimeError('NEUTRAL_TRANSPORT_FAILURE')
 for index in range((v.shard-1)*3,v.shard*3):
  item=cases[index]
  result=s.session(client,item['case'],material,s.PROFILES[0],20261000+index,out/f'qualification-{index+1}',persona='')
  score=old.evaluate(result,item['case'],item['expected']);row={'case_id':item['case']['case_id'],'score':score,'result':result};rows.append(row)
  print('SIM_QUAL_RESULT '+s.canonical(row).decode(),flush=True)
  if result['status']=='transport_error':break
 summary={'planned':3,'completed':len(rows),'model_calls':client.calls,'shard':v.shard,'shard_passed':len(rows)==3 and all(x['score']['eligible'] for x in rows),
  'rows':rows,'human_participants':0,'human_equivalence':'NOT_ESTABLISHED','use_scope':'BOUNDED_SYNTHETIC_DEVELOPMENT_ONLY',
  'qualification_does_not_establish_representativeness':True}
 s.write_json(out/'qualification-shard.json',summary)
 print('SIM_QUAL_TERMINAL '+s.canonical(summary).decode(),flush=True)
 return 0
if __name__=='__main__':raise SystemExit(main())
